name: Test
on: push


concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner_image: ["openjdk-11-lein-2.9.6", "temurin-21-lein-bullseye-slim", "temurin-24-lein-bullseye-slim"]

    container:
      image: clojure:${{ matrix.runner_image }}

    steps:
    - uses: actions/checkout@v4.2.1

    - name: Cache deps
      uses: actions/cache@v4
      with:
        path: /root/.m2
        key: v1-deps-${{ hashFiles('project.clj') }}

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      id: tests
      run: lein test 2>&1

    - name: Verify test file is gone, because shutdown hook deleted it
      run: |
        [[ -e /tmp/ut-test-file ]] && exit 1 || exit 0
