name: Test
on: push


concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:

  test:
    runs-on: ubuntu-latest
    container:
      image: clojure:openjdk-11-lein-2.9.6

    steps:
    - uses: actions/checkout@v2

    - name: Cache deps
      uses: actions/cache@v2
      with:
        path: /root/.m2
        key: v1-deps-${{ hashFiles('project.clj') }}
        restore-keys: |
          v1-deps-${{ hashFiles('project.clj') }}
          v1-deps-

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      id: tests
      run: lein test 2>&1

    - name: Verify test file is gone, because shutdown hook deleted it
      run: |
        [[ -e /tmp/ut-test-file ]] && exit 1 || exit 0
